<a href="https://colab.research.google.com/github/fernando2dias/inteligencia_computacional/blob/main/ex01_introducao_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Centro Universitário Facens<br/></center>
<br/>
<font size="4"><center><b>Disciplina: Inteligência Artificial</b></center></font>
  
<font size="3"><center>Prof. Renato M. Silva</center></font>
<br/>

# <center>Exercício - Introdução ao Python</center>

Neste exercício, são apresentados alguns recursos básicos do Python que geralmente são necessários nos projetos de Ciência de Dados. 

# Numpy - vetores e matrizes

A biblioteca `numpy` do python permite a criação, manipulações e operações matemáticas de vetores e matrizes.

Primeiro, você deve importar a biblioteca, antes de usar suas funções.

In [48]:
# -*- coding: utf-8 -*-

import numpy as np # importa a biblioteca usada para trabalhar com vetores e matrizes.

## Criando vetores e matrizes

Criando um vetor com os seguintes valores $[1,2,3,4,5]$.

In [49]:
# criando um vetor
vet = np.array( [1,2,3,4,5] )
vet2 = np.array( [6,7,8,9,0] )

# você pode imprimir usando a função print ou a função display
print(vet)
display(vet)

print(vet2)
display(vet2)



[1 2 3 4 5]


array([1, 2, 3, 4, 5])

[6 7 8 9 0]


array([6, 7, 8, 9, 0])

Podemos criar um vetor de elementos sequenciais usando a função `arange` do `numpy`. Por exemplo, vamos criar um vetor com valores de 0 até 7.

In [50]:
vet_seq1 = np.arange(8)
vet_seq2 = np.arange(11)

display(vet_seq1)
display(vet_seq2)

array([0, 1, 2, 3, 4, 5, 6, 7])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Agora, vamos criar um vetor de elementos sequenciais de 5 até 10.

In [51]:
vet_seq1 = np.arange(5,11)
vet_seq2 = np.arange(10,20)

display(vet_seq1)
display(vet_seq2)


array([ 5,  6,  7,  8,  9, 10])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Nós podemos também criar um vetor sequencial variando de 2 em 2 ou com outros intervalos.

In [52]:
vet_seq1 = np.arange(5,20,2)
print('Sequência de 5 até 20, variando de 2 em 2:', vet_seq1)

vet_seq1 = np.arange(5,20,5)
print('Sequência de 5 até 20, variando de 5 em 5:', vet_seq1)

vet_seq1 = np.arange(5,20,4)
print('Sequência de 5 até 20, variando de 4 em 4:', vet_seq1)

Sequência de 5 até 20, variando de 2 em 2: [ 5  7  9 11 13 15 17 19]
Sequência de 5 até 20, variando de 5 em 5: [ 5 10 15]
Sequência de 5 até 20, variando de 4 em 4: [ 5  9 13 17]


Vetores sequenciais podem ser usados em laços de repetição. Por exemplo, vamos imprimir todos os valores entre 2 e 10 usando um laço de repetição `for`.

In [53]:
for i in np.arange(2,11):
    print('%d' %i)

2
3
4
5
6
7
8
9
10


Nós também podemos criar um vetor com $n$-zeros ou $n$-uns.

In [54]:
# cria um vetor com 10-zeros
vet_zeros = np.zeros(10)

# cria um vetor com 10-uns
vet_ones = np.ones(10)


print('Vetor de zeros: ', vet_zeros)
print('\nVetor de uns: ', vet_ones)


Vetor de zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Vetor de uns:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Criando uma matriz com os valores: $
  \begin{bmatrix}
    1 & 2 & 3 & 4 & 5 \\
    6 & 7 & 8 & 9 & 10
  \end{bmatrix}$

In [55]:
# cria uma matriz
A = np.array( [[1,2,3,4,5],[6,7,8,9,10]] )

display(A)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Nós também podemos criar uma matriz de valores zero e uma matriz de valores um:

In [56]:
# cria um array de valores zeros com dimensão 2x10
array_zeros = np.zeros( [2,10] )
matriz_test = np.zeros( [10, 10])

# cria um array de valores um com dimensão 2x10
array_ones = np.ones( [2,10] )

print('Vetor de zeros: ')
display(array_zeros)

print('\nVetor de valores um: ')
display(array_ones)

print('\nMatriz de teste:')
display(matriz_test)

Vetor de zeros: 


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


Vetor de valores um: 


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


Matriz de teste:


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Selecionando elementos de vetores e matrizes

Suponha que temos um vetor $[a,b,c,d,e,f,g,h,i]$. Nós podemos selecionar vários subconjuntos de elementos desse vetor, conforme mostrado abaixo. **Observação**: no python, o índice começa a contar em 0.

In [57]:
# criando um vetor
vetA = np.array(['a','b','c','d','e','f','g','h','i'])

print('Três primeiros elementos de vetA: ')
print( vetA[0:3] )

print('\ntodos os valores após o Quinto elementos de vetA: ')
print( vetA[5:] )

print('\nOs três ultimos valores de vetA: ')
print( vetA[-3:] )

print('\nOs valores de vetA entre o 5 elemento até o penúltimo elemento: ')
print( vetA[4:-2], 'ou', vetA[4:7] )

Três primeiros elementos de vetA: 
['a' 'b' 'c']

todos os valores após o Quinto elementos de vetA: 
['f' 'g' 'h' 'i']

Os três ultimos valores de vetA: 
['g' 'h' 'i']

Os valores de vetA entre o 5 elemento até o penúltimo elemento: 
['e' 'f' 'g'] ou ['e' 'f' 'g']


Suponha que temos um array: $\begin{bmatrix}
    1a & 1b & 1c & 1d & 1e & 1f & 1g & 1h & 1i \\
    2a & 2b & 2c & 2d & 2e & 2f & 2g & 2h & 2i \\
    3a & 3b & 3c & 3d & 3e & 3f & 3g & 3h & 3i \\
    4a & 4b & 4c & 4d & 4e & 4f & 4g & 4h & 4i \\
  \end{bmatrix}$.

Nós podemos selecionar vários subconjuntos de elementos dessa matriz, conforme mostrado abaixo.

In [ ]:
# criando uma matriz
arrayA = np.array( [['1a','1b','1c','1d','1e','1f','1g','1h','1i'],
                    ['2a','2b','2c','2d','2e','2f','2g','2h','2i'],
                    ['3a','3b','3c','3d','3e','3f','3g','3h','3i'],
                    ['4a','4b','4c','4d','4e','4f','4g', '4h','4i']])

print('Matriz inteira: ')
print( arrayA )

print('\nTodos os elementos da coluna 3: ')
print( arrayA[:,2] )

print('\nTodos os elementos da linha 2: ')
print( arrayA[1:,:] )

print('\nTodos os elementos das 2 primeiras colunas: ')
print( arrayA[:,0:2] )

print('\nTodos os elementos das 2 primeiras linhas: ')
print( arrayA[0:2,:] )

print('\nApenas os elementos das 2 primeiras linhas e das 2 primeiras colunas: ')
print( arrayA[0:2,0:2] )

print('\nApenas os elementos das 2 últimas linhas e das 4 últimas colunas: ')
print( arrayA[-2:,-4:] )

print('\nApenas os elementos das linhas 2 até 4 e das colunas 4 até 6: ')
print( arrayA[1:3,3:6] )

Matriz inteira: 
[['1a' '1b' '1c' '1d' '1e' '1f' '1g' '1h' '1i']
 ['2a' '2b' '2c' '2d' '2e' '2f' '2g' '2h' '2i']
 ['3a' '3b' '3c' '3d' '3e' '3f' '3g' '3h' '3i']
 ['4a' '4b' '4c' '4d' '4e' '4f' '4g' '4h' '4i']]

Todos os elementos da coluna 3: 
['1c' '2c' '3c' '4c']

Todos os elementos da linha 2: 
[['2a' '2b' '2c' '2d' '2e' '2f' '2g' '2h' '2i']
 ['3a' '3b' '3c' '3d' '3e' '3f' '3g' '3h' '3i']
 ['4a' '4b' '4c' '4d' '4e' '4f' '4g' '4h' '4i']]

Todos os elementos das 2 primeiras colunas: 
[['1a' '1b']
 ['2a' '2b']
 ['3a' '3b']
 ['4a' '4b']]

Todos os elementos das 2 primeiras linhas: 
[['1a' '1b' '1c' '1d' '1e' '1f' '1g' '1h' '1i']
 ['2a' '2b' '2c' '2d' '2e' '2f' '2g' '2h' '2i']]

Apenas os elementos das 2 primeiras linhas e das 2 primeiras colunas: 
[['1a' '1b']
 ['2a' '2b']]

Apenas os elementos das 2 últimas linhas e das 4 últimas colunas: 
[['3f' '3g' '3h' '3i']
 ['4f' '4g' '4h' '4i']]

Apenas os elementos das linhas 2 até 4 e das colunas 4 até 6: 
[['2d' '2e' '2f']
 ['3d' '3e' '3f']]


## Operações básicas com vetores e matrizes

Soma e subtração entre vetores.

In [58]:
A = np.array( [1,2,3] )
B = np.array( [4,5,6] )
print('A:', A);
print('B:', B);

print('\nA+B: ', A+B )
print('A-B: ', A-B )

A: [1 2 3]
B: [4 5 6]

A+B:  [5 7 9]
A-B:  [-3 -3 -3]


Soma e subtração entre matrizes.

In [59]:
X1 = np.array( [[1,2,3],
                [4,5,6]] )

X2 = np.array( [[4,5,6],
                [7,8,9]])

print('X1: \n', X1);
print('\nX2: \n', X2);

print('\nX1+X2:')
display(X1+X2)

print('\nX1-X2:')
display(X1-X2)

X1: 
 [[1 2 3]
 [4 5 6]]

X2: 
 [[4 5 6]
 [7 8 9]]

X1+X2:


array([[ 5,  7,  9],
       [11, 13, 15]])


X1-X2:


array([[-3, -3, -3],
       [-3, -3, -3]])

Produto entre duas matrizes.

In [ ]:
A = np.array( ([[1,2],[3,4],[5,6]]) )
B = np.array( ([[1,2,3,4],[5,6,7,8]]) )

print('A: ')
display(A)

print('B: ')
display(B)

print('A*B: ')
display(np.dot(A,B)) 

A: 


array([[1, 2],
       [3, 4],
       [5, 6]])

B: 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

A*B: 


array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

Média dos valores de uma matriz.

In [ ]:
print('B: ')
display(B)

# média das linhas de B
media1 = np.mean(B, axis = 1)
print('\nMédia das linhas de B: ')
display(media1)

# média das colunas de B
media2 = np.mean(B, axis = 0)
print('\nMédia das colunas de B: ')
display(media2)

# média de todos os valores de B 
media3 = np.mean(B)
print('\nMédia de todos os valores de B: ')
display(media3)

B: 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])


Média das linhas de B: 


array([2.5, 6.5])


Média das colunas de B: 


array([3., 4., 5., 6.])


Média de todos os valores de B: 


4.5

Desvio padrão dos valores de uma matriz.

In [ ]:
print('B: ')
display(B)

# desvio padrão das linhas de B
std1 = np.std(B, axis = 1, ddof=1)
print('\nDesvio padrão das linhas de B: ')
display(std1)

# desvio padrão das colunas de B
std2 = np.std(B, axis = 0, ddof=1)
print('\nDesvio padrão das colunas de B: ')
display(std2)

# desvio padrão de todos os valores de B 
std3 = np.std(B, ddof=1)
print('\nDesvio padrão de todos os valores de B: ')
display(std3)

B: 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])


Desvio padrão das linhas de B: 


array([1.29099445, 1.29099445])


Desvio padrão das colunas de B: 


array([2.82842712, 2.82842712, 2.82842712, 2.82842712])


Desvio padrão de todos os valores de B: 


2.449489742783178

Outras funções para vetores e matrizes.
* `np.min()` &rarr; valor mínimo
* `np.max()` &rarr; valor máximo
* `np.sort(A)` &rarr; retorna o vetor $A$ ordenado
* `np.argsort(A)` &rarr; retorna os índices do vetor $A$ ordenado
* `np.var()` &rarr; variância
* `np.shape()` &rarr; dimensões da matriz
* `np.transpose()` &rarr; transposta da matriz
* `np.concatenate(arrays, axis=numero_do_eixo)` &rarr; concatena vetores ou matrizes
* `vstack(A,B)` &rarr; empilha verticalmente
* `hstack(A,B)` &rarr; empilha horizontalmente
* `np.where(A>n)` &rarr; elementos em $A$ maiores que $n$

## Exercícios

**Ex. 1**. Crie duas matrizes com os nomes $ExA$ e $ExB$ preenchidas com os seguintes valores:

$ExA = \begin{bmatrix}
    12 & 9 & 4 & 1 \\
    11 & 5 & 8 & 1 \\
    1 & 2 & 3 & 1 \\
  \end{bmatrix}
$, 
$
ExB = \begin{bmatrix}
    1 & 5 \\
    1 & 7 \\
    1 & 9 \\
    1 & 1 \\
  \end{bmatrix}
$. Após isso, imprima as duas matrizes.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExA = np.array([[12,9,4,1],[11,5,8,1],[1,2,3,1]])
print('\nMatriz ExA:')
display(ExA)

ExB = np.array([[1,5],[1,7],[1,9],[1,1]])
print('\nMatrizExB')
display(ExB)

##########################################################################


Matriz ExA:


array([[12,  9,  4,  1],
       [11,  5,  8,  1],
       [ 1,  2,  3,  1]])


MatrizExB


array([[1, 5],
       [1, 7],
       [1, 9],
       [1, 1]])

**Ex. 2**. Crie uma matriz $ExC$ usando a seguinte operação: $ExC = ExA \cdot ExB$. Depois, imprima $ExC$. 

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExC = np.dot(ExA,ExB)
print('\nMatrizExC = ExA x ExB')
display(ExC)

##########################################################################


MatrizExC = ExA x ExB


array([[ 26, 160],
       [ 25, 163],
       [  7,  47]])

**Ex. 3**. Crie uma função que retorne a média e o desvio padrão das linhas de uma matriz e a média e desvio padrão das colunas de uma matriz. Depois teste sua função com a matriz $ExC$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################

desvio_padrao_lin_ExC = np.std(ExC, axis = 1, ddof=1)
print('\nDesvio padrão linhas ExC')
display(desvio_padrao_lin_ExC)

desvio_padrao_col_ExC = np.std(ExC, axis = 0, ddof=1)
print('\nDesvio padrão colunas ExC')
display(desvio_padrao_col_ExC)
##########################################################################


Desvio padrão linhas ExC


array([94.75230868, 97.5807358 , 28.28427125])


Desvio padrão colunas ExC


array([10.69267662, 66.1236216 ])

**Ex. 4**. Crie uma matriz $ExD$ com os valores das duas últimas colunas de $ExA$. Depois, calcule a média dos valores de $ExD$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExD =  ExA[:,-2:] 
display(ExD)

##########################################################################

array([[4, 1],
       [8, 1],
       [3, 1]])

**Ex. 5**. Crie uma matriz $ExE$ com os valores das linhas 1 e 2 e das colunas 1 e 2 de $ExA$.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExE = ExA[0:2, 0:2]
display(ExE)

##########################################################################

array([[12,  9],
       [11,  5]])

**Ex. 6**. Crie e imprima uma matriz $ExF$ com 5 linhas e 2 colunas e todos os valores iguais a 0.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExF = np.zeros([5,2]) 
display(ExF)
##########################################################################

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**Ex. 7**. Crie e imprima uma matriz $ExG$ com 4 linhas e 3 colunas e todos os valores iguais a 1.

In [ ]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
ExG = np.ones([4,3])
display(ExG)

##########################################################################

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Ex. 8**. Crie uma função que retorne o fatorial de um número. Teste a função que você criou, calculando o fatorial de 8. 

Fórmula do fatorial: $n! = (1 * 2 * 3 * ... * (n-2) * (n-1) * n)$

Obs: é obrigatório usar um laço `for`. 

Exemplos: 
* $1! = 1$
* $2! = 1*2$
* $3! = 1*2*3$
* $4! = 1*2*3*4$
* $5! = 1*2*3*4*5$

In [62]:
################# ESCREVA SEU CÓDIGO AQUI  ###############################
result=1
print=""
i=1

print(result)

##########################################################################

TypeError: ignored